version: '3.8'

services:
  backend:
    build: .
    container_name: backend-service
    ports:
      - "5050:5050"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
